def build_markdown_report(records):
    """Membangun tabel markdown dari data mahasiswa."""
    header = "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |\n|---|---|---:|---:|:---:|"
    rows = [
        f"| {r['nim']} | {r['nama']} | {r['hadir']} | {r['nilai']} | {r['predikat']} |"
        for r in records
    ]
    return "# Rekap Nilai Mahasiswa\n\n" + header + "\n" + "\n".join(rows) + "\n\nGenerated by student_performance_tracker"

def save_text(path, content):
    """Menyimpan teks ke file .md."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def build_html_report(records):
    """Membuat laporan HTML berwarna berdasarkan predikat."""
    colors = {"A": "#aaffaa", "B": "#ccffcc", "C": "#ffffcc", "D": "#ffcccc", "E": "#ff9999"}
    rows = "".join([
        f"<tr style='background:{colors.get(r['predikat'],'white')}'><td>{r['nim']}</td><td>{r['nama']}</td><td>{r['hadir']}</td><td>{r['nilai']}</td><td>{r['predikat']}</td></tr>"
        for r in records
    ])
    html = f"""
    <html><head><title>Rekap Nilai</title></head>
    <body>
    <h2>Rekap Nilai Mahasiswa</h2>
    <table border='1' cellpadding='5'>
    <tr><th>NIM</th><th>Nama</th><th>Hadir (%)</th><th>Nilai Akhir</th><th>Predikat</th></tr>
    {rows}
    </table>
    <p>Generated by student_performance_tracker</p>
    </body></html>
    """
    return html